model_name: "MTG gameplay text price range classifier"

experiment_path: "/Users/{tu_email_de_usuario}"

distilbert_model: "distilbert-base-uncased-finetuned-sst-2-english"

test_size: 0.2

tokenizer_args:
  padding: "max_length"
  max_length: 194

training_args:
  output_dir: "./results"
  evaluation_strategy: "epoch"
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_train_epochs: 3
  weight_decay: 0.01
  logging_dir: "./logs"